'use strict';
const url = require('url');
const _ = require('lodash');
// const resolve = require('resolve');
// const path = require('path');
const levelup = require('level');
const levelgraph = require("levelgraph");

// Libs
exports.libs = {
  lodash: _,
  cheerio: require('cheerio'),
  simplecrawler: require('simplecrawler')
};

// Database
exports.graphdb = (loc) => levelgraph(levelup(loc || `${__dirname}/tmp/db`));

// Selectors
exports.select = (() => { 
  function external(domain) {
    let notInternal = 'a[href^=http]';
    let notSub = ':not([href*=".' + domain + '"])';
    let notRoot = ':not([href*="/' + domain + '"])';
    
    return notInternal + notSub + notRoot;
  };

  function internal(domain) {
    let Internal = 'a:not([href^=http])';
    let Sub = ', a[href*=".' + domain + '"]';
    let Root = ', a[href*="/' + domain + '"]';

    return Internal + Sub + Root;
  };
  
  return {
    external,
    internal,
    // aliases
    e: external,
    i: internal
  };
})();


// Filters
exports.filter = (() => {
  function blacklist(input, blacklist) {
    return _.filter(input, (t) => !blacklist.some((good) => _.includes(t, good)));
  };
  
  function whitelist(input, whitelist) {
    return _.filter(input, (t) => whitelist.some((good) => _.includes(t, good)));
  };
  
  return {
    blacklist,
    whitelist,
    b: blacklist,
    w: whitelist
  };
})();

// Others
exports.notEmpty = (arr) => arr.length > 0;
exports.hostname = (link) => url.parse(link).hostname;

exports.links = function(cheerio_array, cheerio_instance) {
  return cheerio_array.map((i, el) => cheerio_instance(el).attr("href")).get();
};

exports.noSub = function(host) {
  var parts = host.split(".");
  if (parts.length > 2) { parts = parts.slice(1); }
  return parts.join('.');
};


// 500 most popular sites on the internet: useful for blacklisting to not crawl
exports.alexa500 = [
  "adf.ly",
  "360.com",
  "youku.com",
  "adobe.com",
  "google.com.eg",
  "daum.net",
  "bbc.co.uk",
  "haosou.com",
  "163.com",
  "booking.com",
  "google.com.sa",
  "google.co.th",
  "google.com.pk",
  "chase.com",
  "google.com.ar",
  "alipay.com",
  "flipkart.com",
  "livedoor.jp",
  "quora.com",
  "china.com",
  "nytimes.com",
  "espn.go.com",
  "google.nl",
  "sogou.com",
  "ebay.co.uk",
  "akamaihd.net",
  "xfinity.com",
  "csdn.net",
  "google.ch",
  "twimg.com",
  "bestbuy.com",
  "google.pt",
  "roblox.com",
  "google.cz",
  "about.com",
  "wordreference.com",
  "usps.com",
  "t-online.de",
  "1688.com",
  "xywy.com",
  "doorblog.jp",
  "google.cl",
  "intuit.com",
  "onedio.com",
  "buzzhand.com",
  "sourceforge.net",
  "google.ae",
  "icicibank.com",
  "bitauto.com",
  "youtube-mp3.org",
  "allegro.pl",
  "popcash.net",
  "fbcdn.net",
  "wix.com",
  "americanexpress.com",
  "google.at",
  "upornia.com",
  "wikimedia.org",
  "google.dz",
  "theladbible.com",
  "hdfcbank.com",
  "terraclicks.com",
  "onet.pl",
  "spotify.com",
  "irctc.co.in",
  "files.wordpress.com",
  "blog.jp",
  "webtretho.com",
  "weebly.com",
  "pandora.com",
  "shutterstock.com",
  "capitalone.com",
  "google.cn",
  "hulu.com",
  "wordpress.org",
  "bilibili.com",
  "ebay.de",
  "amazon.cn",
  "dailymotion.com",
  "bbc.com",
  "xnxx.com",
  "amazonaws.com",
  "adnetworkperformance.com",
  "txxx.com",
  "indiatimes.com",
  "bankofamerica.com",
  "china.com.cn",
  "ettoday.net",
  "buzzfeed.com",
  "zhihu.com",
  "ameblo.jp",
  "zillow.com",
  "dailymail.co.uk",
  "soundcloud.com",
  "salesforce.com",
  "uol.com.br",
  "tudou.com",
  "vice.com",
  "google.com.ua",
  "indeed.com",
  "chinadaily.com.cn",
  "google.com.mx",
  "apple.com",
  "aliexpress.com",
  "fc2.com",
  "gmw.cn",
  "diply.com",
  "imdb.com",
  "google.co.kr",
  "github.com",
  "google.ca",
  "pornhub.com",
  "amazon.de",
  "office.com",
  "ok.ru",
  "google.com.hk",
  "google.com.tr",
  "kat.cr",
  "rakuten.co.jp",
  "whatsapp.com",
  "alibaba.com",
  "nicovideo.jp",
  "ask.com",
  "craigslist.org",
  "blogger.com",
  "ebay-kleinanzeigen.de",
  "trello.com",
  "chaturbate.com",
  "media.tumblr.com",
  "mercadolivre.com.br",
  "groupon.com",
  "2ch.net",
  "wp.pl",
  "livejasmin.com",
  "goodreads.com",
  "xcar.com.cn",
  "amazon.es",
  "ltn.com.tw",
  "businessinsider.com",
  "speedtest.net",
  "xuite.net",
  "espncricinfo.com",
  "tokopedia.com",
  "oracle.com",
  "abs-cbn.com",
  "kaskus.co.id",
  "paytm.com",
  "rediff.com",
  "google.co.il",
  "ruten.com.tw",
  "ebay.com",
  "reddit.com",
  "google.co.uk",
  "amazon.co.jp",
  "t.co",
  "google.com.br",
  "google.fr",
  "mail.ru",
  "pinterest.com",
  "tmall.com",
  "netflix.com",
  "microsoft.com",
  "360.cn",
  "google.it",
  "onclickads.net",
  "wordpress.com",
  "tumblr.com",
  "google.es",
  "blogspot.com",
  "imgur.com",
  "sohu.com",
  "paypal.com",
  "naver.com",
  "stackoverflow.com",
  "xvideos.com",
  "freepik.com",
  "nba.com",
  "sabah.com.tr",
  "ouo.io",
  "google.no",
  "digikala.com",
  "bukalapak.com",
  "bloomberg.com",
  "extratorrent.cc",
  "cloudfront.net",
  "hotstar.com",
  "siteadvisor.com",
  "agar.io",
  "medium.com",
  "macys.com",
  "repubblica.it",
  "sahibinden.com",
  "billdesk.com",
  "instructure.com",
  "airbnb.com",
  "likes.com",
  "taleo.net",
  "verizonwireless.com",
  "wsj.com",
  "messenger.com",
  "godaddy.com",
  "offerjuice.me",
  "dmm.co.jp",
  "uptodown.com",
  "weather.com",
  "onlinesbi.com",
  "google.com.co",
  "gfycat.com",
  "naver.jp",
  "redtube.com",
  "directrev.com",
  "bet365.com",
  "torrentz.eu",
  "taringa.net",
  "9gag.com",
  "force.com",
  "pixiv.net",
  "vimeo.com",
  "blogspot.in",
  "varzesh3.com",
  "slither.io",
  "kakaku.com",
  "putlocker.is",
  "amazon.it",
  "steampowered.com",
  "google.com",
  "youtube.com",
  "facebook.com",
  "baidu.com",
  "yahoo.com",
  "wikipedia.org",
  "amazon.com",
  "twitter.com",
  "qq.com",
  "google.co.in",
  "live.com",
  "taobao.com",
  "bing.com",
  "google.co.jp",
  "msn.com",
  "yahoo.co.jp",
  "linkedin.com",
  "sina.com.cn",
  "weibo.com",
  "vk.com",
  "instagram.com",
  "google.ru",
  "yandex.ru",
  "google.de",
  "hao123.com",
  "google.ie",
  "1905.com",
  "ndtv.com",
  "icloud.com",
  "kinopoisk.ru",
  "fedex.com",
  "blastingnews.com",
  "slack.com",
  "liveadexchanger.com",
  "sberbank.ru",
  "webmd.com",
  "addthis.com",
  "hurriyet.com.tr",
  "51yes.com",
  "liputan6.com",
  "milliyet.com.tr",
  "samsung.com",
  "mailchimp.com",
  "badoo.com",
  "telegraph.co.uk",
  "ppomppu.co.kr",
  "gizmodo.com",
  "cnnic.cn",
  "loading-delivery2.com",
  "dell.com",
  "google.pl",
  "pixnet.net",
  "google.co.id",
  "jd.com",
  "xhamster.com",
  "googleusercontent.com",
  "amazon.in",
  "xinhuanet.com",
  "soso.com",
  "dropbox.com",
  "google.com.au",
  "go.com",
  "outbrain.com",
  "tianya.cn",
  "amazon.co.uk",
  "cntv.cn",
  "bongacams.com",
  "coccoc.com",
  "microsoftonline.com",
  "wikia.com",
  "twitch.tv",
  "cnn.com",
  "popads.net",
  "google.com.tw",
  "youth.cn",
  "hatena.ne.jp",
  "amazon.ca",
  "spiegel.de",
  "gearbest.com",
  "bild.de",
  "merdeka.com",
  "box.com",
  "tabelog.com",
  "meaww.com",
  "mashable.com",
  "hm.com",
  "ebay.in",
  "alicdn.com",
  "marca.com",
  "mi.com",
  "olx.pl",
  "vk.me",
  "eastday.com",
  "expedia.com",
  "blogimg.jp",
  "gmanetwork.com",
  "thesportbible.com",
  "azlyrics.com",
  "ameba.jp",
  "ancestry.com",
  "hatenablog.com",
  "thefreedictionary.com",
  "kickstarter.com",
  "ck101.com",
  "zippyshare.com",
  "surveymonkey.com",
  "leagueoflegends.com",
  "engadget.com",
  "reuters.com",
  "elpais.com",
  "umblr.com",
  "wetransfer.com",
  "blog-newstime.com",
  "rt.com",
  "kissanime.to",
  "lifehacker.com",
  "realtor.com",
  "free.fr",
  "blogspot.jp",
  "okezone.com",
  "telegram.org",
  "asos.com",
  "donga.com",
  "yallakora.com",
  "thewatchseries.to",
  "libero.it",
  "avg.com",
  "4shared.com",
  "ask.fm",
  "naukri.com",
  "friv.com",
  "google.sk",
  "impress.co.jp",
  "savefrom.net",
  "nownews.com",
  "enet.com.cn",
  "java.com",
  "citi.com",
  "cnblogs.com",
  "acfun.tv",
  "lifebuzz.com",
  "trackingclick.net",
  "google.dk",
  "livedoor.com",
  "sh.st",
  "cricbuzz.com",
  "dictionary.com",
  "openload.co",
  "jabong.com",
  "ebay.it",
  "tradeadexchange.com",
  "life.tw",
  "nyaa.se",
  "buzzlie.com",
  "blackboard.com",
  "adplxmd.com",
  "themeforest.net",
  "exoclick.com",
  "dmm.com",
  "ign.com",
  "att.com",
  "imzog.com",
  "rutracker.org",
  "rambler.ru",
  "evernote.com",
  "gsmarena.com",
  "doublepimp.com",
  "sharepoint.com",
  "39.net",
  "tube8.com",
  "blogfa.com",
  "lowes.com",
  "scribd.com",
  "blkget.com",
  "livedoor.biz",
  "tribunnews.com",
  "nih.gov",
  "taboola.com",
  "flickr.com",
  "tripadvisor.com",
  "softonic.com",
  "google.com.pe",
  "google.ro",
  "feedly.com",
  "google.com.ng",
  "bp.blogspot.com",
  "foxnews.com",
  "google.be",
  "github.io",
  "w3schools.com",
  "rdsa2012.com",
  "washingtonpost.com",
  "hclips.com",
  "iqiyi.com",
  "youporn.com",
  "udn.com",
  "skype.com",
  "deviantart.com",
  "douyu.com",
  "tistory.com",
  "ups.com",
  "slickdeals.net",
  "caijing.com.cn",
  "pinimg.com",
  "eksisozluk.com",
  "hp.com",
  "accuweather.com",
  "battle.net",
  "google.hu",
  "zendesk.com",
  "yesky.com",
  "kompas.com",
  "huanqiu.com",
  "seznam.cz",
  "thesaurus.com",
  "reimageplus.com",
  "secureserver.net",
  "mama.cn",
  "kinogo.co",
  "mlb.com",
  "archive.org",
  "giphy.com",
  "mediab.uy",
  "usatoday.com",
  "kapanlagi.com",
  "wellsfargo.com",
  "slideshare.net",
  "mediafire.com",
  "walmart.com",
  "nametests.com",
  "so.com",
  "globo.com",
  "etsy.com",
  "google.co.ve",
  "huffingtonpost.com",
  "google.co.za",
  "avito.ru",
  "myway.com",
  "yelp.com",
  "google.gr",
  "doubleclick.net",
  "detail.tmall.com",
  "stackexchange.com",
  "cnzz.com",
  "aol.com",
  "steamcommunity.com",
  "cnet.com",
  "theguardian.com",
  "goo.ne.jp",
  "detik.com",
  "zol.com.cn",
  "livejournal.com",
  "amazon.fr",
  "wittyfeed.com",
  "comcast.net",
  "ikea.com",
  "web.de",
  "homedepot.com",
  "google.com.sg",
  "target.com",
  "mozilla.org",
  "orange.fr",
  "mega.nz",
  "ifeng.com",
  "snapdeal.com",
  "wikihow.com",
  "google.se",
  "leboncoin.fr",
  "forbes.com",
  "youm7.com",
  "thepiratebay.se",
  "google.com.ph",
  "gmx.net",
  "babytree.com",
  "51.la"
];
